In [1]:
import numpy as np

In [3]:
arr1=np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


# SLICING ARRAY


In [4]:
print(arr1[2:7])

[2 3 4 5 6]


In [5]:
print(arr1[::2])

[0 2 4 6 8]


In [6]:
arr_slice=arr1[5:8]
print(arr_slice)

[5 6 7]


In [7]:
arr_slice[1]=99
print(arr1)

[ 0  1  2  3  4  5 99  7  8  9]


In [8]:
arr2=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
print(arr2[1,2])

7


In [11]:
print(arr2[:2,1:3])

[[2 3]
 [6 7]]


In [12]:
a=np.array([1,2,3,4])
print(a+1)
print(a-1)
print(a*2)
print(a**2)
print(a/2)

[2 3 4 5]
[0 1 2 3]
[2 4 6 8]
[ 1  4  9 16]
[0.5 1.  1.5 2. ]


In [15]:
arr=np.array([[1,4,5,7],[6,8,9,3],[2,11,13,15]])
print(arr.max())
print(arr.max(axis=1))
print(arr.min(axis=0))
print(arr.sum())
print(arr.cumsum(axis=1))


15
[ 7  9 15]
[1 4 5 3]
84
[[ 1  5 10 17]
 [ 6 14 23 26]
 [ 2 13 26 41]]


In [16]:
c=np.array([[1,2],[3,4]])
d=np.array([[5,6],[7,8]])
print(c+d)
print(c*d)
print(c.dot(d))


[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


In [18]:
arr2=np.array([0,np.pi/2,np.pi])
print(arr2)
print(np.sin(arr2))
print(np.cos(arr2))
print(np.exp(arr2))
print(np.sqrt(arr2))


[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 1.          4.81047738 23.14069263]
[0.         1.25331414 1.77245385]


In [19]:
h=np.array([[1,5,6],[-1,8,3],[0,9,4]])
print(np.sort(h))
print(np.sort(h,axis=0))
print(np.sort(h,axis=1))



[[ 1  5  6]
 [-1  3  8]
 [ 0  4  9]]
[[-1  5  3]
 [ 0  8  4]
 [ 1  9  6]]
[[ 1  5  6]
 [-1  3  8]
 [ 0  4  9]]


In [20]:
dtypes=[('Name','S10'),('Dob',int),('cgpa',float)]
values=[('Mansi',2005,9.8),('Yatika',2005,8.9),('Ayush',2004,9.9),('Aryan',2004,8.7)]
arr0=np.array(values,dtype=dtypes)
print(np.sort(arr0,order='Name'))
print(np.sort(arr0,order=['Dob','cgpa']))

[(b'Aryan', 2004, 8.7) (b'Ayush', 2004, 9.9) (b'Mansi', 2005, 9.8)
 (b'Yatika', 2005, 8.9)]
[(b'Aryan', 2004, 8.7) (b'Ayush', 2004, 9.9) (b'Yatika', 2005, 8.9)
 (b'Mansi', 2005, 9.8)]


In [24]:
a = np.array([[1,2,3,4],[7,6,2,0]])
print(a)
print(np.min(a))
#Specify axis for the direction in case of multidim array
print(np.min(a,axis=0))
print(np.min(a,axis=1))


[[1 2 3 4]
 [7 6 2 0]]
0
[1 2 2 0]
[1 0]


In [26]:
arr5=([1,2,3,4,5])
m=sum(arr5)/5
print(m)
print(np.mean(arr5))
print(np.mean(arr5,axis=0))
print(np.median(arr5))


3.0
3.0
3.0
3.0
