In [10]:
import numpy as np

In [3]:
print(np.__version__)

2.1.3


In [4]:
print(np.show_config())

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/himan/anaconda3/Library/include
    lib directory: C:/Users/himan/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/himan/anaconda3/Library/include
    lib directory: C:/Users/himan/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_25aj347ekn\croot\numpy_and_numpy_base_1730835595898\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30156
  cython:
    commands: cython
    linker: cython
    name: cython
  

In [7]:
# null vector of size 10
a=np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [15]:
arr=np.zeros(8)
print(arr.size)
print(arr.nbytes)

8
64


In [17]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its or

In [22]:
b=np.zeros(10)
b[5]=1
print(b)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [35]:
vec=np.arange(10,50)
print(vec)
vec[::-1]

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [51]:
# Create 0-8 first, then reshape it into 3x3
matrix = np.random.random((3,3,3))
print(matrix)

[[[0.42731224 0.42463351 0.61619799]
  [0.91624066 0.20599228 0.93897809]
  [0.30390232 0.0123296  0.39379047]]

 [[0.79919213 0.05933955 0.30061054]
  [0.20405873 0.65607137 0.38118181]
  [0.1184339  0.19474256 0.7567874 ]]

 [[0.24460166 0.60135057 0.87063248]
  [0.00221914 0.93704136 0.52152651]
  [0.37965998 0.58271005 0.44271616]]]


In [44]:
p=np.array([1,2,0,0,4,0])
arr=np.nonzero(p)
print(arr)

(array([0, 1, 4]),)


mat=np.eye(3)
print(mat)

In [54]:
matr=np.random.random((10,10))
print(matr)
print(matr.min())
print(matr.max())

[[0.75548754 0.65431995 0.17719099 0.82378673 0.83284752 0.36700465
  0.12575887 0.37474013 0.44942155 0.22608433]
 [0.88070943 0.20606697 0.10936947 0.35901909 0.22453993 0.2443589
  0.4616957  0.65440792 0.92256868 0.58632222]
 [0.54203    0.23947911 0.00656844 0.47948749 0.06651049 0.51380127
  0.90574387 0.03410461 0.46810799 0.08273519]
 [0.55878536 0.69785905 0.42224604 0.20143127 0.66908033 0.83673617
  0.17223869 0.04964535 0.20987328 0.10593296]
 [0.82046037 0.16975028 0.85320396 0.68914458 0.15325942 0.87135898
  0.05026521 0.12598174 0.78088383 0.83586197]
 [0.11191354 0.20574483 0.78660685 0.39161902 0.6427782  0.41318247
  0.18462566 0.90218707 0.69888686 0.11110786]
 [0.82894601 0.24581078 0.93453233 0.55582925 0.4867748  0.60951597
  0.63225132 0.45860634 0.46370118 0.01330949]
 [0.18001647 0.65289426 0.75486785 0.72456968 0.79477147 0.26967065
  0.53834299 0.27583634 0.75354536 0.22168981]
 [0.20909956 0.94455404 0.20873466 0.40644116 0.52266555 0.88314932
  0.83310262 

In [57]:
m=np.random.random((30))
print(m.mean())

0.5683589025931735


In [58]:
import os 
print(os.getcwd())


C:\Users\himan\Pyhton_jupyter
