In [1]:
!pip3 install numpy

In [2]:
import numpy as np


In [3]:
arr=np.array([[1,2,3],[4,5,6]])

In [4]:
type(arr) #type of array

numpy.ndarray

In [5]:
arr.ndim #dimensions of array

2

In [6]:
arr.shape # shape of array

(2, 3)

In [7]:
arr.size # size of array(tells total  number of elements)

6

In [8]:
arr.dtype # type of elements

dtype('int64')

In [9]:
a=np.array([[1,2,3],[4,5,6]],dtype='float')
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [10]:
b=np.array((1,2,3))
print(b)

[1 2 3]


In [11]:
c=np.zeros((3,2))
print(c)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [12]:
d=np.ones((2,3))
print(d)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
e = np.full((3, 3), 6, dtype = 'complex')
print(e)

[[6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]
 [6.+0.j 6.+0.j 6.+0.j]]


In [14]:
f = np.random.random((2,2))
print(f)

[[0.80605174 0.46057194]
 [0.40050093 0.37748265]]


In [15]:
g=np.arange(0,30,5)
print(g)

[ 0  5 10 15 20 25]


In [16]:
h=np.linspace(0,30,5)
print(h)

[ 0.   7.5 15.  22.5 30. ]


In [17]:
# an exemplar array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# slicing
temp = arr[:2, ::2]
print(temp)

[[-1.  0.]
 [ 4.  6.]]


In [18]:
temp = arr[[0, 1, 2, 3], [3, 2, 1, 0]]
print("\nElements at indices (0, 3), (1, 2), (2, 1), (3, 0):\n", temp)



Elements at indices (0, 3), (1, 2), (2, 1), (3, 0):
 [4. 6. 0. 3.]


In [19]:
a = np.array([1, 2, 5, 3])

# add 1 to every element
print("Adding 1 to every element:", a+1)

# subtract 3 from each element
print("Subtracting 3 from each element:", a-3)

# multiply each element by 10
print("Multiplying each element by 10:", a*10)

# square each element
print("Squaring each element:", a**2)

# modify existing array
a *= 2
print("Doubled each element of original array:", a)

# transpose of array 
a = np.array([[1, 2, 3], [3, 4, 5], [9, 6, 0]])
print("\nOriginal array:\n", a)
print("Transpose of array:\n", a.T)

Adding 1 to every element: [2 3 6 4]
Subtracting 3 from each element: [-2 -1  2  0]
Multiplying each element by 10: [10 20 50 30]
Squaring each element: [ 1  4 25  9]
Doubled each element of original array: [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]
Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]
